### ISSUE TITLE
@supabase/ssr - multiple OAuth broken [Nextjs]

### ISSUE THREAD

**Issue by 0x-Legend** [supabase/auth-helpers#668]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When a user signs up using one form of authentication (email/password or any OAuth method), signin works correctly if they keep using that original method.

But if they try and sign in using another method such as:
- signing up with email/password, then signing in with Google, or
- signing up with Google, then  signing in with Github, or
- signing up with Github, then signing in with Google

Auth starts becoming buggy. Sometimes users can't even signin using their original method for sign up, leaving them completely unable to access their account.

I confirmed this is not expected behavior with a mod from the supabase discord. This is also likely a bug since I am able to achieve multiple auth (email/password ,google, github for one account) when handling everything through the auth-helpers package.

Some flows that I have tested:
1. Sign up using email/password --> sign in using github (success) --> sign in using email/password (success) --> sign in using github (success) = (so using email/password & github works)
2. Sign up using email/password --> sign in using google (success) --> sign in using email/password (success) --> **sign in using google (fail)** = (so using email/password & google doesn't work)
3. Sign up using email/password --> sign in using github (success) --> **sign in using google (fail)** --> **sign in using github (fail)** --> sign in using email/password (success) = (looks like something wrong with google?)
4. Sign up with any OAuth provider prevents normal email/password sign up afterwards (I think this was possible in auth helpers, not sure). = (the response from supabase.auth.signUp is successful but no email is recieved to confirm sign up nor is the password set)
5. Sign up with github (success) --> sign in with google (fail) --> sign in with github (fail) --> sign in with magic link (fail - supabase.auth.signInWithOtp returns error) --> sign up with email/password (fail - supabase.auth.signUp returns error) = this is the worst case where the user has no way of signing in.
6. There are likely more test cases to consider as there are so many auth providers. For example, github seems to partially working, but google and discord is more broken, and so on.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'https://github.com/0x-Legend/Nextjs-14-Supabase-Starter'
2. Clone the commit hash: 'b48983d6e675386190a34ec1599d9b0290afb8c9'
3. Set up supabase and link env variables (I'm hosted on Vercel).
4. Navigate to '/login' page and test

## Expected behavior

Using multiple forms of authentication should work as it did when using auth-helpers package.

## Screenshots

N/A

## System information

- OS: macOS 14.0
- Browser: Chrome
- Version of @supabase/ssr: 0.0.5
- Version of Node.js: 20.3.1

**Comment by ja3nyc** [comment]
I was able to fix the issue with multiple provider by adding the import, `import { combineChunks, createChunks, deleteChunks } from '@supabase/ssr'`, in the `createServerClient` "get", "set", and "remove" of my code since the size of the cookie trying to get stored was too large. 

This is how I implemented into '/utils/server.ts'
`
import { createServerClient, type CookieOptions, combineChunks, createChunks  } from '@supabase/ssr'
import { cookies } from 'next/headers'

export const createClient = (cookieStore: ReturnType<typeof cookies>) => {
  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          const value = cookieStore.get(name)?.value
          if (name.endsWith('-code-verifier') || value)
            return value

          const chunk = combineChunks(name, (chunks) => cookieStore.get(chunks)?.value)
          return chunk ?? null
        },
        set(name: string, value: string, options: CookieOptions) {
          try {
            
            const sessionChunks = createChunks(name, value, 2500)

            sessionChunks.forEach((sess)=> {
              cookieStore.set({ name: sess.name, value: sess.value, ...options })
            })
            // cookieStore.set({ name, value, ...options })
          } catch (error) {
            // The `set` method was called from a Server Component.
            // This can be ignored if you have middleware refreshing
            // user sessions.
            console.log(error)
          }
        },
        remove(name: string, options: CookieOptions) {
          try {
            const cookie = cookieStore.get(name)
            if (cookie)
              cookieStore.set({ name, value: '', ...options })
            else {
              const chunkNames: string[] = [];
              const getCookies = cookieStore.getAll()
              getCookies.forEach((cookie) => {
                if (cookie.name.startsWith(name))
                  chunkNames.push(cookie.name)
              })
              chunkNames.forEach((chunkName) => {
                cookieStore.set({ name: chunkName, value: '', ...options })
              })
            }
            
          } catch (error) {
            // The `delete` method was called from a Server Component.
            // This can be ignored if you have middleware refreshing
            // user sessions.
          }
        },
      },
    }
  )
}
`

From what I read on the discord, it seems the cookie chunking isn't added to the docs yet. Not sure if this is the recommended implementation of it, but it seems to fix the issue I was facing.

**Comment by 0x-Legend** [comment]
> I was able to fix the issue with multiple provider by adding the import, `import { combineChunks, createChunks, deleteChunks } from '@supabase/ssr'`, in the `createServerClient` "get", "set", and "remove" of my code since the size of the cookie trying to get stored was too large.
> 
> This is how I implemented into '/utils/server.ts'
> 
> ```
> import { createServerClient, type CookieOptions, combineChunks, createChunks  } from '@supabase/ssr'
> import { cookies } from 'next/headers'
> 
> export const createClient = (cookieStore: ReturnType<typeof cookies>) => {
>   return createServerClient(
>     process.env.NEXT_PUBLIC_SUPABASE_URL!,
>     process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
>     {
>       cookies: {
>         get(name: string) {
>           const value = cookieStore.get(name)?.value
>           if (name.endsWith('-code-verifier') || value)
>             return value
> 
>           const chunk = combineChunks(name, (chunks) => cookieStore.get(chunks)?.value)
>           return chunk ?? null
>         },
>         set(name: string, value: string, options: CookieOptions) {
>           try {
>             
>             const sessionChunks = createChunks(name, value, 2500)
> 
>             sessionChunks.forEach((sess)=> {
>               cookieStore.set({ name: sess.name, value: sess.value, ...options })
>             })
>             // cookieStore.set({ name, value, ...options })
>           } catch (error) {
>             // The `set` method was called from a Server Component.
>             // This can be ignored if you have middleware refreshing
>             // user sessions.
>             console.log(error)
>           }
>         },
>         remove(name: string, options: CookieOptions) {
>           try {
>             const cookie = cookieStore.get(name)
>             if (cookie)
>               cookieStore.set({ name, value: '', ...options })
>             else {
>               const chunkNames: string[] = [];
>               const getCookies = cookieStore.getAll()
>               getCookies.forEach((cookie) => {
>                 if (cookie.name.startsWith(name))
>                   chunkNames.push(cookie.name)
>               })
>               chunkNames.forEach((chunkName) => {
>                 cookieStore.set({ name: chunkName, value: '', ...options })
>               })
>             }
>             
>           } catch (error) {
>             // The `delete` method was called from a Server Component.
>             // This can be ignored if you have middleware refreshing
>             // user sessions.
>           }
>         },
>       },
>     }
>   )
> }
> ```
> 
> From what I read on the discord, it seems the cookie chunking isn't added to the docs yet. Not sure if this is the recommended implementation of it, but it seems to fix the issue I was facing.

Interesting, I'll have to test this out then. it seems GitHub auth is just flawed in general. Doesn't work properly even on auth-helpers. 

If you have multiple emails linked to your GitHub account:
1. foo@github.com
2. boo@github.com
3. coo@github.com

And you have two separate email/password account using:
1. foo@github.com
2. boo@github.com

You won't be able to use login with GitHub at all because I think GitHub shares all emails and supabase auth gets confused.

**Comment by 0x-Legend** [comment]
So if we ignore the github flows I tested, we still have some issues.

The following flows work with auth-helpers, but not ssr, and it might just be due to cookies being too large like you said.

Flow:
1. Sign up using Google (success) --> Sign in using Discord (fail)
2. Sign up using Discord (success) --> Sign in using Google (fail)
3. Sign up using Email/Password (success) --> Sign in using Google (pass) --> Sign in using Google (fail)
4. Sign up using Email/Password (success) --> Sign in using Discord (pass) --> Sign in using Discord (fail)

**Comment by LHDi** [comment]
This seems to be a cookie size issue, and it's fixed by #669

**Comment by 0x-Legend** [comment]
> This seems to be a cookie size issue, and it's fixed by #669

Looks like it's still pending review and merge. Will report back once they release it

**Comment by silentworks** [comment]
We just released version 0.0.6 of the `@supabase/ssr` package which should address this. Please report back here if the issue has been resolved or if it's still not working for you.

**Comment by 0x-Legend** [comment]
> We just released version 0.0.6 of the `@supabase/ssr` package which should address this. Please report back here if the issue has been resolved or if it's still not working for you.

Still facing the issues mentioned in this comment above: https://github.com/supabase/auth-helpers/issues/668#issuecomment-1791489839

**Comment by orenaksakal** [comment]
Still experiencing the error with 0.0.6 (google oauth)

**Comment by silentworks** [comment]
I've fouund the issue. I'm getting another release out shortly with the fix.

**Comment by cgladish** [comment]
Thanks @silentworks. Appreciate the help!

**Comment by orenaksakal** [comment]
0.0.7 seems to work thanks a lot for taking care of it @silentworks !

**Comment by 0x-Legend** [comment]
Thank you @silentworks, 0.0.7 solves it! Closing this.

**Comment by cgladish** [comment]
solved for me as well! thanks @silentworks
