### ISSUE TITLE
auth-helpers-shared: "Session from session_id claim in JWT does not exist error"

### ISSUE THREAD

**Issue by rsimon** [supabase/auth-helpers#804]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

We've been getting the above error message ("AuthApiError: Session from session_id claim in JWT does not exist") when accessing `supabase.auth.getUser()` on the server (SSR) right after successful log-in, after switching from `@supabase/auth-helpers-shared@0.3.4` to `@0.7.0`.

Weirdly enough, the problem doesn't _always_ occur, almost as if a timing issue were involved somewhere. But certainly in the majority of attempts.

## To Reproduce

* We are logging the user in, in the browser, and are getting the `SIGNED_IN` event in the `supabase.auth.onAuthStateChange` handler.
* At this point, we grab `access_token` and `refresh_token` from the session, and are setting cookies.
* The user is then redirectred to a protected route.
* On the server (SSR, our app is using Astro 4), we:
  * create a Supabase client using `auth-helper-shared` (which works for us)
  * set a new session based on `access_token`  and `refresh_token` (again: works)
  * call `supabase.auth.getUser()` to get the user object (fails with the above error)

We use the following code on the server to create the supabase client. This code is run every time a user visits a protected route.

```js
import { createSupabaseClient, type SupabaseClientOptionsWithoutAuth } from '@supabase/auth-helpers-shared';

export async function initClient(
  cookies: AstroCookies,
  {
    supabaseUrl,
    supabaseKey,
    options
  }: {
    supabaseUrl: string;
    supabaseKey: string;
    options?: SupabaseClientOptionsWithoutAuth;
  }
) {
  const client = createSupabaseClient(
    supabaseUrl,
    supabaseKey,
    {
      ...options,
      global: {
        ...options?.global,
        headers: {
          ...options?.global?.headers
        }
      },
      auth: {
        storage: {
          getItem: (name: string) => cookies.get(name)?.value,

          setItem: (name: string, value: string) => cookies.set(name, value),

          removeItem: (name: string) => cookies.delete(name)
        }
      }
    }
  );

  await refreshSession(client, cookies);
  return client;
}

const refreshSession = async (supabase: SupabaseClient, cookies: AstroCookies) => {  
  const { data: { session }} = await supabase.auth.getSession();
  if (session) return true;

  const refreshToken = cookies.get('sb-refresh-token');
  const accessToken = cookies.get('sb-access-token');

  if (refreshToken?.value && accessToken?.value) {
    return await supabase.auth.setSession({ 
      refresh_token: refreshToken.value, 
      access_token: accessToken.value 
    }).then(({ error }) => {
      return !error
    })
}
```

Aditionally, here's our code for retrieving the user object. Likewise, this gets called each time the user visits a protected route.

```js
export const getUser = (supabase: SupabaseClient): Promise<User> =>
  supabase.auth.getUser().then(({ error, data }) => {
    if (error) {
      throw error;
    } else if (data.user === null) {
      throw 'Unauthorized';
    } else if (data.user.role !== 'authenticated') {
      throw 'Unauthorized';
    } else {
      return data.user;
    }
  });
```

## Expected behavior

We can confirm that every time the user hits a protected route...

* ...the supabase client gets created correctly.
* ...the session is either valid (or gets correctly refreshed). We can log the session, and see the correct login user data in the log.
* Yet, when calling `supabase.auth.getUser()` immediately afterwards, we're getting `Session from session_id claim in JWT does not exist error` 

## System information

- OS: MacOS
- Browser (if applies) Chrome & Safari (tested - but probably not relevant to this particular issue)
- Version of supabase-js: 2.44.4
- Version of Node.js: v18.18

## Additional context

* I believe this is a regression bug in `@supabase/auth-helpers-shared`. But I cannot rule out that it's us, doing something stupid somewhere. Let me know if you have any ideas on what might be going wrong, or if I can provide any additional info to help diagnose the issue.
* FWIW: it seems we are seeing this issue only (or at least more often) with users that have more than one identity in the `auth.identities` table.

**Comment by andrew-app** [comment]
I am also experiencing this issue in Next.js 14 with `@supabase/ssr@0.4.0`. I am calling `supabase.auth.getUser()` in middleware as mentioned in [docs](https://supabase.com/docs/guides/auth/server-side/creating-a-client?queryGroups=environment&environment=middleware). This bug occurs in the following:
- User logs in by calling `supabase.auth.signInWithPassword()` from a client component login page.
- User is now logged in, I show a page with a button to logout, user clicks logout button and gets redirected to `/logout`
- `/logout` is a server component that calls `supabase.auth.signOut()` and redirects user back to login page
- "Session from session_id claim in JWT does not exist" error gets logged when calling supabase.auth.getUser() from middleware

The [docs](https://supabase.com/docs/guides/auth/server-side/nextjs) suggest using server actions to do login I will try that see if i get the same error.

https://github.com/user-attachments/assets/56cf451a-eb87-40dd-9e96-4d63e6c8146c

**Comment by gary-lo** [comment]
+1 Getting the same isssue

**Comment by gary-lo** [comment]
+1 getting the same issue - support told us to just update to SSR - glad I found this thread first

**Comment by gary-lo** [comment]
Very similar where it's intermittent. 

<img width="632" alt="image" src="https://github.com/user-attachments/assets/5f5fc220-7e43-4f0f-8ae0-4a7d456ec27f">

What we also experimented is - we've taken a copy of the network request as a CURL. We replay it some time after with the same JWT and it'll work.

**Comment by ygill-impel** [comment]
Hi We are also having the issue with this when we send jwt from Remix app to the backend FastAPI server to validate request function.

**Comment by SkycladObserver** [comment]
Hello, we are experiencing this issue as well. This only started occurring when we refresh the session. From experience, it seems having multiple sessions from different devices increases the frequency, but it's still not consistent.

**Comment by gurkiranksingh** [comment]
I'm also experiencing this issue on logging out the user - also intermittent.

**Comment by JUDE-EQ** [comment]
having the same issue with our app. `supabase.auth.signOut()` triggers the same error. any updates?

**Comment by finallyblueskies** [comment]
Experiencing the same issue on `supabase.auth.signOut`

**Comment by JeffK-IM** [comment]
Same issue here!

**Comment by seanc** [comment]
I'm encountering this as well with Deno backend using the `https://esm.sh/@supabase/supabase-js@2.38.4?pin=v135` package. I have middleware that verifies whether the token is valid and it passes but when trying to use the token with client using the following:

```ts
  const authHeader = ctx.request.headers.get("Authorization")!;
  const userSupabaseClient = getSupabaseClient(authHeader);

  const { data: user } = await userSupabaseClient.auth.getUser();
  ```
  
  I get this error:
  ```
  [api-prod] [2024-11-25 03:05:24] Error occurred: AuthApiError: Session from session_id claim in JWT does not exist
[api-prod] [2024-11-25 03:05:24]     at le (https://esm.sh/v135/@supabase/gotrue-js@2.57.0/denonext/gotrue-js.mjs:2:5284)
[api-prod] [2024-11-25 03:05:24]     at eventLoopTick (ext:core/01_core.js:175:7)
[api-prod] [2024-11-25 03:05:24]     at async Ie (https://esm.sh/v135/@supabase/gotrue-js@2.57.0/denonext/gotrue-js.mjs:2:6071)
[api-prod] [2024-11-25 03:05:24]     at async h (https://esm.sh/v135/@supabase/gotrue-js@2.57.0/denonext/gotrue-js.mjs:2:5808)
[api-prod] [2024-11-25 03:05:24]     at async https://esm.sh/v135/@supabase/gotrue-js@2.57.0/denonext/gotrue-js.mjs:2:26221
[api-prod] [2024-11-25 03:05:24]     at async g._useSession (https://esm.sh/v135/@supabase/gotrue-js@2.57.0/denonext/gotrue-js.mjs:2:25010)
[api-prod] [2024-11-25 03:05:24]     at async g._getUser (https://esm.sh/v135/@supabase/gotrue-js@2.57.0/denonext/gotrue-js.mjs:2:26138)
[api-prod] [2024-11-25 03:05:24]     at async https://esm.sh/v135/@supabase/gotrue-js@2.57.0/denonext/gotrue-js.mjs:2:26001
[api-prod] [2024-11-25 03:05:24]     at async https://esm.sh/v135/@supabase/gotrue-js@2.57.0/denonext/gotrue-js.mjs:2:24296 {
[api-prod] [2024-11-25 03:05:24]   __isAuthError: true,
[api-prod] [2024-11-25 03:05:24]   name: "AuthApiError",
[api-prod] [2024-11-25 03:05:24]   status: 403
[api-prod] [2024-11-25 03:05:24] }
```

**Comment by tanmays** [comment]
Encountering the same issue, I have multiple sessions of the same user active. I have an edge function that verifies current user. 

Relevant code: 
```
// Create a Supabase client with the Auth context of the logged in user
const supabaseClient = createClient(
  Deno.env.get('SUPABASE_URL') ?? '',
  Deno.env.get('SUPABASE_ANON_KEY') ?? '',
  { global: { headers: { Authorization: authHeader } } }
)

// Check if the user is authenticated
const { data: { user }, error: authError } = await supabaseClient.auth.getUser()
if (authError) {
  throw new Error(`Authentication error: ${authError.message}`)
}
if (!user) {
  throw new Error('User not found')
}
```

Error:
`Error: Authentication error: Session from session_id claim in JWT does not exist`

More Details:
`"served_by": "supabase-edge-runtime-1.65.3 (compatible with Deno v1.45.2)"`

**Comment by MultiX0** [comment]
i have the same exact issue with get request via supabase api

**Comment by MultiX0** [comment]
Hey everyone,

I ran into the exact same issue using the Supabase API with Go. After logging in, I’d try to fetch user info with the access token, but often got this error:

    AuthApiError: Session from session_id claim in JWT does not exist

It was super frustrating, especially since it seemed to happen more often for users with multiple identities in the auth.identities table.
How I Fixed It:

I found that refreshing the session before making any request with the token did the trick. So, I added a call to `supabase.auth.refreshSession()` right before sending the request, and that solved the problem.

Hope this helps someone else out there dealing with the same headache!

**Comment by MultiX0** [comment]
> # Bug report
> 
>     * [x]  I confirm this is a bug with Supabase, not with my own application.
> 
>     * [x]  I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com).
> 
> 
> ## Describe the bug
> 
> We've been getting the above error message ("AuthApiError: Session from session_id claim in JWT does not exist") when accessing `supabase.auth.getUser()` on the server (SSR) right after successful log-in, after switching from `@supabase/auth-helpers-shared@0.3.4` to `@0.7.0`.
> 
> Weirdly enough, the problem doesn't _always_ occur, almost as if a timing issue were involved somewhere. But certainly in the majority of attempts.
> ## To Reproduce
> 
>     * We are logging the user in, in the browser, and are getting the `SIGNED_IN` event in the `supabase.auth.onAuthStateChange` handler.
> 
>     * At this point, we grab `access_token` and `refresh_token` from the session, and are setting cookies.
> 
>     * The user is then redirected to a protected route.
> 
>     * At this point, we can also see in the browser that all cookies (including the auth token) and localStorage token are correctly set.
> 
>     * On the server (SSR, our app is using Astro 4), we:
>       
>       * create a Supabase client using `auth-helper-shared` (which works for us)
>       * set a new session based on `access_token`  and `refresh_token` (again: works)
>       * call `supabase.auth.getUser()` to get the user object (fails with the above error)
> 
> 
> We use the following code on the server to create the supabase client. This code is run every time a user visits a protected route.
> 
> ```js
> import { createSupabaseClient, type SupabaseClientOptionsWithoutAuth } from '@supabase/auth-helpers-shared';
> 
> export async function initClient(
>   cookies: AstroCookies,
>   {
>     supabaseUrl,
>     supabaseKey,
>     options
>   }: {
>     supabaseUrl: string;
>     supabaseKey: string;
>     options?: SupabaseClientOptionsWithoutAuth;
>   }
> ) {
>   const client = createSupabaseClient(
>     supabaseUrl,
>     supabaseKey,
>     {
>       ...options,
>       global: {
>         ...options?.global,
>         headers: {
>           ...options?.global?.headers
>         }
>       },
>       auth: {
>         storage: {
>           getItem: (name: string) => cookies.get(name)?.value,
> 
>           setItem: (name: string, value: string) => cookies.set(name, value),
> 
>           removeItem: (name: string) => cookies.delete(name)
>         }
>       }
>     }
>   );
> 
>   await refreshSession(client, cookies);
>   return client;
> }
> 
> const refreshSession = async (supabase: SupabaseClient, cookies: AstroCookies) => {  
>   const { data: { session }} = await supabase.auth.getSession();
>   if (session) return true;
> 
>   const refreshToken = cookies.get('sb-refresh-token');
>   const accessToken = cookies.get('sb-access-token');
> 
>   if (refreshToken?.value && accessToken?.value) {
>     return await supabase.auth.setSession({ 
>       refresh_token: refreshToken.value, 
>       access_token: accessToken.value 
>     }).then(({ error }) => {
>       return !error
>     })
> }
> ```
> 
> Aditionally, here's our code for retrieving the user object. Likewise, this gets called each time the user visits a protected route, immediately after creating our client.
> 
> ```js
> export const getUser = (supabase: SupabaseClient): Promise<User> =>
>   supabase.auth.getUser().then(({ error, data }) => {
>     if (error) {
>       throw error;
>     } else if (data.user === null) {
>       throw 'Unauthorized';
>     } else if (data.user.role !== 'authenticated') {
>       throw 'Unauthorized';
>     } else {
>       return data.user;
>     }
>   });
> ```
> 
> ## Expected behavior
> 
> We can confirm that every time the user hits a protected route...
> 
>     * ...the supabase client gets created correctly.
> 
>     * ...the session is either valid, or gets correctly refreshed.
> 
>     * We can log the session to console.log, and see the correct login user data.
> 
>     * Yet, when calling `supabase.auth.getUser()`, we're getting `Session from session_id claim in JWT does not exist error`.
> 
> 
> ## System information
> 
>     * OS: MacOS
> 
>     * Browser (if applies) Chrome & Safari (tested - but probably not relevant to this particular issue)
> 
>     * Version of supabase-js: 2.44.4
> 
>     * Version of Node.js: v18.18, v20.15.0 (tested)
> 
> 
> ## Additional context
> 
>     * I believe this is a regression bug in `@supabase/auth-helpers-shared`. But I cannot rule out that it's us, doing something stupid somewhere. Let me know if you have any ideas on what might be going wrong, or if I can provide any additional info to help diagnose the issue.
> 
>     * FWIW: it seems we are seeing this issue only (or at least more often) with users that have more than one identity in the `auth.identities` table.
> 
>     * I'm not sure if this is in any way related to [this discussion](https://github.com/orgs/supabase/discussions/23715)?

Hey everyone,

I ran into the exact same issue using the Supabase API with Go. After logging in, I’d try to fetch user info with the access token, but often got this error:

    AuthApiError: Session from session_id claim in JWT does not exist

It was super frustrating, especially since it seemed to happen more often for users with multiple identities in the auth.identities table.
How I Fixed It:

I found that refreshing the session before making any request with the token did the trick. So, I added a call to `supabase.auth.refreshSession()` right before sending the request, and that solved the problem.

Hope this helps someone else out there dealing with the same headache!

**Comment by MultiX0** [comment]
@rsimon 

Hey everyone,

I ran into the exact same issue using the Supabase API with Go. After logging in, I’d try to fetch user info with the access token, but often got this error:

    AuthApiError: Session from session_id claim in JWT does not exist

It was super frustrating, especially since it seemed to happen more often for users with multiple identities in the auth.identities table.
How I Fixed It:

I found that refreshing the session before making any request with the token did the trick. So, I added a call to `supabase.auth.refreshSession()` right before sending the request, and that solved the problem.

Hope this helps someone else out there dealing with the same headache!

**Comment by fubits1** [comment]
Landed here from investigating a 403 logout issue (https://github.com/supabase/auth-helpers/issues/804)

Can confirm that this problem still arises and I couldn't tame it with try/catch in the client.

However, in my case (SvelteKit) the problem is related to setting a path when creating the client server-side:

```
setAll: (cookiesToSet) => {
  cookiesToSet.forEach(({ name, value, options }) => {
    event.cookies.set(name, value, { ...options, path: '/' }) 
  })
}
```

Since I'm deploying to a subpath '/project', I set the path option accordingly. Reverting to '/' fixes the 403 / missing session (after clearing cookies). And turns out that the cookie is still set properly with the correct sub-path '/project' so that was a bit unexpected behaviour... 

Dependencies:
- @supabase/ssr@0.5.2
- @supabase/supabase-js@2.47.8
- @sveltejs/kit@2.11.1

and supabase/gotrue:v2.165.1-rc.5 on the Server (tested from as low as v2.159.2)
